Update python-package.yml

diff --git a/.github/workflows/python-package.yml b/.github/workflows/python-package.yml
--- a/.github/workflows/python-package.yml
+++ b/.github/workflows/python-package.yml
@@ -38,3 +38,5 @@ jobs:
     - name: Test with pytest
       run: |
         pytest
+    - name: Test with pytest
+      run: pytest --co -q || true   # ignore exit code
